version: '3.9'
services:
  postgres:
    image: postgres:17-alpine
    container_name: mente-saudavel-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mentesaudavel
    ports:
      - "5432:5432"
    volumes:
      - mente-saudavel-data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "10000:80"
    depends_on:
      - postgres

volumes:
  mente-saudavel-data:
